name: Java push to nexus test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Nexus Repository Publish
        # You may pin to the exact commit or the version.
        # uses: sonatype-nexus-community/nexus-repo-github-action@f8178e57b79477b7b98b1ae94a4d77ba9c1bf731
        uses: myqld/nexus-repo-github-action@main
        with:
          # Nexus Repository Server URL
          serverUrl: https://maven.devops.myqld.developer.qld.gov.au/
          # Username to connect to Nexus Repo to publish components
          username: "${{ secrets.MAVEN_USER }}"
          # Password to connect to Nexus Repo to publish components
          password: "${{ secrets.MAVEN_PW }}"
          # Component format e.g. maven2
          format: maven2
          # Name of target repository on Nexus Repo e.g. maven-releases
          repository: maven-releases
          # Component coordinates in key=value format. e.g. groupId=com.example artifactId=app version=1.0.0
          coordinates: "groupId=com.example artifactId=myapp version=1.0"
          # Component assets in key=value format. e.g. extension=jar
          assets: filename=example-1.0.jar
          # File to publish
          filename: ./test/resources/example-1.0.jar